### PR TITLE
Switch to Hiera 5

### PR DESCRIPTION
**Pull request by smortex**

### CODE REVIEW

**Comment by smortex** [comment]
This will conflict with #3.  I will rebase a PR on top of master when the other one get merged.

**Comment by smortex** [comment]
Rebased on top of master

**Comment by neomilium** [comment]
Please confirm: if we apply this PR, we will not be able to use official debian package from stretch on a puppet master, except if we copy default values, right ?

**Comment by smortex** [comment]
Yes, Hiera 5 was added in Puppet 4.9.0:
https://puppet.com/docs/puppet/4.9/release_notes.html#new-features

**Pull request merged**
